version: '2'
services:
  web:
    image: dockercloud/hello-world
    environment:
      VIRTUAL_HOST: web2.dev
    labels:
      - lb.hook=true
    networks:
      - network

networks:
  network:
    # Use a custom driver
    driver: bridge